In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
a1 = np.array([[1, 2, 4], [4, 5, 7], [7, 8, 90]])
print(a1)

[[ 1  2  4]
 [ 4  5  7]
 [ 7  8 90]]


In [6]:
a1.ravel()

array([ 1,  2,  4,  4,  5,  7,  7,  8, 90])

In [7]:
a1>=5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [9]:
((a1<=5)*(a1>=90))%3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [21]:
a1[1]

array([4, 5, 7])

In [22]:
a1[:,2]

array([ 4,  7, 90])

In [27]:
a1[1:,2]

array([ 7, 90])

In [28]:
a1[1:,:2]

array([[4, 5],
       [7, 8]])